### PR TITLE
implement fallback to basic authentication when GSSAPI/Negotiate fails

### PR DESCRIPTION
**Pull request by neptunao**
Conflicts:
	ngx_http_auth_spnego_module.c

### CODE REVIEW

**Comment by Neptunao** [comment]
@stnoonan please review. I've done all that you ask in the https://github.com/stnoonan/spnego-http-auth-nginx-module/pull/28

**Comment by pesovo** [comment]
thanks to your PR, it is very helpfull for my solition.

**Comment by aperigault** [comment]
There is something that block merge ?

**Comment by neptunao** [comment]
@stnoonan ping

**Pull request merged**
